### ISSUE TITLE
Jester fails on project with zero tests

### ISSUE THREAD

**Issue by Lutger** [jauco/jester#15] opened 2015-02-02 09:22 UTC
This is what happens when you don't have any tests (yet):

>Chrome 39.0.2171 (Linux): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
>Firefox 34.0.0 (Linux): Executed 0 of 0 ERROR (0 secs / 0 secs)
>Karma server has finished with 1
>Finished with errors, not all tests or lints succeeded.

I'd expect it not to fail, or fail with a clearer error message.

**Comment by jauco** [comment] 2015-02-02 09:28
Hmm, this is by design https://github.com/karma-runner/karma/issues/926 though I could improve karma's error message. 

0 tests in a CI environment would almost always be a failure because you can easily add 1 passing test and it might be because of a gross misconfiguration which would otherwise go unnoticed

**Comment by jauco** [comment] 2015-02-02 14:33
Can be fixed by fixing https://github.com/karma-runner/karma/issues/926

**Comment by jauco** [comment] 2015-04-20 19:51
Closing this. I don't see why you'd want to run jester and not have any unittests. Just write some.

**Closed by jauco** 2015-04-20 19:51 UTC
Labels: bug, Pull Request welcome
